# ghoshell.llms.thinks.conversational.ConversationalConfig
name: chat/baseline
reactions:
  cancel: ghoshell.ghost_fmk.reactions.cancel_cmd
  restart: ghoshell.ghost_fmk.reactions.restart_cmd
  quit: ghoshell.ghost_fmk.reactions.quit_cmd
  task: ghoshell.ghost_fmk.reactions.task_cmd
  process: ghoshell.ghost_fmk.reactions.process_cmd
  instance_count: ghoshell.ghost_fmk.reactions.instance_count_cmd
  thought: ghoshell.ghost_fmk.reactions.thought_cmd
  redirect: ghoshell.ghost_fmk.reactions.redirect_cmd

