use_command_cache: true
use_llm_config: turbo-16k-0613
simple_command_mode:
  name: "sphero/simple_command_mode"
  welcome: "进入单一命令模式, 请给我下达指令"
  debug: false
learning_mode:
  name: sphero/learning_mode